import Foundation

struct SimpleCurlImporter: CurlImporting {
    func parse(_ rawInput: String) throws -> CurlImportResult {
        let trimmed = rawInput.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else {
            throw CurlImportError.emptyInput
        }

        let tokens = try ShellTokenizer.tokenize(Self.normalizeLineContinuations(in: trimmed))
        let curlTokens = try Self.canonicalBytePipelineCurlTokens(from: tokens) ?? tokens
        let command = try CurlCommandParser().parse(curlTokens)
        let request = try CurlRequestMapper().map(command)

        return CurlImportResult(
            request: request,
            warnings: command.warnings,
            sourceCurl: trimmed
        )
    }

    private static func normalizeLineContinuations(in input: String) -> String {
        var output = ""
        var index = input.startIndex

        while index < input.endIndex {
            if input[index] == "\\" {
                var lookahead = input.index(after: index)
                while lookahead < input.endIndex, input[lookahead] == " " || input[lookahead] == "\t" {
                    lookahead = input.index(after: lookahead)
                }

                if lookahead < input.endIndex, input[lookahead] == "\n" {
                    output.append(" ")
                    index = input.index(after: lookahead)
                    continue
                }

                if lookahead < input.endIndex, input[lookahead] == "\r" {
                    let afterCarriageReturn = input.index(after: lookahead)
                    if afterCarriageReturn < input.endIndex, input[afterCarriageReturn] == "\n" {
                        output.append(" ")
                        index = input.index(after: afterCarriageReturn)
                        continue
                    }
                }
            }

            output.append(input[index])
            index = input.index(after: index)
        }

        return output
    }

    private static func canonicalBytePipelineCurlTokens(from tokens: [String]) throws -> [String]? {
        guard tokens.first == "printf" else {
            return nil
        }
        guard tokens.count >= 8,
              tokens[1] == "%b",
              tokens[3] == "|",
              tokens[4] == "curl" else {
            throw CurlImportError.unsupportedSyntax("Only Curly-generated byte-safe cURL pipelines are supported.")
        }

        let body = try decodeCanonicalOctalBytes(tokens[2])
        var curlTokens = Array(tokens.dropFirst(4))
        guard let dataOptionIndex = curlTokens.firstIndex(of: "--data-binary"),
              curlTokens.indices.contains(dataOptionIndex + 1),
              curlTokens[dataOptionIndex + 1] == "@-",
              !curlTokens.dropFirst(dataOptionIndex + 2).contains("|") else {
            throw CurlImportError.unsupportedSyntax("Only Curly-generated byte-safe cURL pipelines are supported.")
        }
        curlTokens[dataOptionIndex] = "--data-raw"
        curlTokens[dataOptionIndex + 1] = body
        return curlTokens
    }

    private static func decodeCanonicalOctalBytes(_ value: String) throws -> String {
        let characters = Array(value)
        guard !characters.isEmpty, characters.count.isMultiple(of: 4) else {
            throw CurlImportError.unsupportedSyntax("The Curly byte-safe body encoding is malformed.")
        }

        var bytes: [UInt8] = []
        for offset in stride(from: 0, to: characters.count, by: 4) {
            guard characters[offset] == "\\" else {
                throw CurlImportError.unsupportedSyntax("The Curly byte-safe body encoding is malformed.")
            }
            let digits = String(characters[(offset + 1)...(offset + 3)])
            guard digits.allSatisfy({ $0 >= "0" && $0 <= "7" }),
                  let byte = UInt8(digits, radix: 8) else {
                throw CurlImportError.unsupportedSyntax("The Curly byte-safe body encoding is malformed.")
            }
            bytes.append(byte)
        }
        return String(decoding: bytes, as: UTF8.self)
    }
}

private struct CurlCommand {
    var method: HTTPMethod?
    var url: String?
    var headers: [Header] = []
    var suppressedHeaderNames: Set<String> = []
    var bodyParts: [String] = []
    var usesDataBody = false
    var disablesTLSCertificateVerification = false
    var warnings: [String] = []

    mutating func setMethod(_ newMethod: HTTPMethod, source: String) {
        if let method, method != newMethod {
            warnings.append("Method from `\(source)` overrides earlier method \(method.rawValue).")
        }
        method = newMethod
    }

    mutating func appendHeader(name: String, value: String) {
        suppressedHeaderNames.remove(name.lowercased())
        headers.append(Header(name: name, value: value, isEnabled: true))
    }

    mutating func suppressHeader(name: String) {
        let normalizedName = name.lowercased()
        headers.removeAll { $0.name.lowercased() == normalizedName }
        suppressedHeaderNames.insert(normalizedName)
    }
}

private struct CurlCommandParser {
    private let registry = CurlOptionRegistry()

    func parse(_ tokens: [String]) throws -> CurlCommand {
        guard tokens.first == "curl" else {
            throw CurlImportError.notCurl
        }

        var command = CurlCommand()
        var index = 1

        while index < tokens.count {
            let token = tokens[index]

            if token.hasPrefix("-") {
                let parsedOptions = try parseOptionTokens(token)
                if parsedOptions.count > 1 {
                    for parsedOption in parsedOptions {
                        guard let definition = registry.definition(named: parsedOption.name) else {
                            continue
                        }
                        try definition.behavior.apply(value: nil, token: parsedOption.name, command: &command)
                    }
                    index += 1
                    continue
                }

                let parsedOption = parsedOptions[0]
                guard let definition = registry.definition(named: parsedOption.name) else {
                    command.warnings.append("Ignored unsupported cURL flag `\(parsedOption.name)`.")
                    index += 1
                    continue
                }

                switch definition.arity {
                case .none:
                    try definition.behavior.apply(value: nil, token: parsedOption.name, command: &command)
                    index += 1
                case .requiredValue:
                    let value: String
                    if let attachedValue = parsedOption.attachedValue {
                        value = attachedValue
                    } else {
                        index += 1
                        guard index < tokens.count else {
                            throw CurlImportError.malformedInput("Missing value after \(parsedOption.name).")
                        }
                        value = tokens[index]
                    }
                    try definition.behavior.apply(value: value, token: parsedOption.name, command: &command)
                    index += 1
                }

                continue
            }

            if command.url == nil {
                command.url = token
            } else {
                throw CurlImportError.malformedInput("Unexpected extra token '\(token)'.")
            }
            index += 1
        }

        return command
    }

    private func parseOptionTokens(_ token: String) throws -> [ParsedCurlOption] {
        if let separator = token.firstIndex(of: "="), token.hasPrefix("--") {
            let name = String(token[..<separator])
            let value = String(token[token.index(after: separator)...])
            return [ParsedCurlOption(name: name, attachedValue: value)]
        }

        for shortName in ["-X", "-H", "-d", "-A", "-b", "-u", "-F"] where token.hasPrefix(shortName) && token != shortName {
            let value = String(token.dropFirst(shortName.count))
            guard !value.isEmpty else {
                break
            }
            return [ParsedCurlOption(name: shortName, attachedValue: value)]
        }

        if token.hasPrefix("-"), !token.hasPrefix("--"), token.count > 2 {
            let bundledOptions = token.dropFirst().map {
                ParsedCurlOption(name: "-\($0)", attachedValue: nil)
            }
            let containsOnlyNoValueOptions = bundledOptions.allSatisfy { option in
                guard let definition = registry.definition(named: option.name) else {
                    return false
                }
                if case .none = definition.arity {
                    return true
                }
                return false
            }
            if containsOnlyNoValueOptions {
                return bundledOptions
            }
        }

        return [ParsedCurlOption(name: token, attachedValue: nil)]
    }
}

private struct ParsedCurlOption {
    var name: String
    var attachedValue: String?
}

private struct CurlOptionRegistry {
    private let definitions: [CurlOptionDefinition]

    init() {
        definitions = [
            CurlOptionDefinition(names: ["-X", "--request"], arity: .requiredValue, behavior: .requestMethod),
            CurlOptionDefinition(names: ["-H", "--header"], arity: .requiredValue, behavior: .header),
            CurlOptionDefinition(names: ["-d", "--data", "--data-raw", "--data-binary", "--data-ascii", "--data-urlencode"], arity: .requiredValue, behavior: .body),
            CurlOptionDefinition(names: ["--json"], arity: .requiredValue, behavior: .jsonBody),
            CurlOptionDefinition(names: ["--url"], arity: .requiredValue, behavior: .url),
            CurlOptionDefinition(names: ["-A", "--user-agent"], arity: .requiredValue, behavior: .headerValue(name: "User-Agent")),
            CurlOptionDefinition(names: ["-b", "--cookie"], arity: .requiredValue, behavior: .cookie),
            CurlOptionDefinition(names: ["-c", "--cookie-jar"], arity: .requiredValue, behavior: .warnValue("Cookie jar files are not represented yet.")),
            CurlOptionDefinition(names: ["-u", "--user"], arity: .requiredValue, behavior: .basicAuth),
            CurlOptionDefinition(names: ["-I", "--head"], arity: .none, behavior: .head),
            CurlOptionDefinition(names: ["-L", "--location"], arity: .none, behavior: .ignore),
            CurlOptionDefinition(names: ["-i", "--include"], arity: .none, behavior: .warn("Ignored terminal output flag `-i`.")),
            CurlOptionDefinition(names: ["-w", "--write-out"], arity: .requiredValue, behavior: .warnValue("Ignored terminal write-out flag.")),
            CurlOptionDefinition(names: ["-v", "--verbose"], arity: .none, behavior: .warn("Ignored terminal output flag `-v`.")),
            CurlOptionDefinition(names: ["-s", "--silent"], arity: .none, behavior: .warn("Ignored terminal output flag `-s`.")),
            CurlOptionDefinition(names: ["--fail", "--fail-with-body"], arity: .none, behavior: .warn("Ignored terminal failure handling flag.")),
            CurlOptionDefinition(names: ["--compressed"], arity: .none, behavior: .ignore),
            CurlOptionDefinition(names: ["-F", "--form", "--form-string"], arity: .requiredValue, behavior: .multipartForm),
            CurlOptionDefinition(names: ["-o", "--output", "-D", "--dump-header"], arity: .requiredValue, behavior: .warnValue("Ignored file output flag.")),
            CurlOptionDefinition(names: ["-O", "--remote-name"], arity: .none, behavior: .warn("Ignored file output flag.")),
            CurlOptionDefinition(names: ["--proxy", "-x", "--proxy-user", "--proxy-header"], arity: .requiredValue, behavior: .warnValue("Proxy options are not represented yet.")),
            CurlOptionDefinition(names: ["--cacert", "--cert", "--key", "--cert-type", "--key-type"], arity: .requiredValue, behavior: .warnValue("TLS client options are not represented yet.")),
            CurlOptionDefinition(names: ["--connect-timeout", "--max-time", "--retry"], arity: .requiredValue, behavior: .warnValue("Request timing/retry options are not represented yet.")),
            CurlOptionDefinition(names: ["--insecure", "-k"], arity: .none, behavior: .disableTLSCertificateVerification),
            CurlOptionDefinition(names: ["--http1.1", "--http2", "--http3", "--no-progress-meter", "--progress-bar"], arity: .none, behavior: .warn("Ignored transport/display flag."))
        ]
    }

    func definition(named name: String) -> CurlOptionDefinition? {
        definitions.first { $0.names.contains(name) }
    }
}

private struct CurlOptionDefinition {
    var names: Set<String>
    var arity: CurlOptionArity
    var behavior: CurlOptionBehavior
}

private enum CurlOptionArity {
    case none
    case requiredValue
}

private enum CurlOptionBehavior {
    case requestMethod
    case header
    case body
    case jsonBody
    case url
    case headerValue(name: String)
    case cookie
    case basicAuth
    case head
    case multipartForm
    case disableTLSCertificateVerification
    case ignore
    case warn(String)
    case warnValue(String)

    func apply(value: String?, token: String, command: inout CurlCommand) throws {
        switch self {
        case .requestMethod:
            guard let value else { return }
            guard let method = HTTPMethod(rawValue: value.uppercased()) else {
                throw CurlImportError.unsupportedSyntax("Unsupported HTTP method \(value).")
            }
            command.setMethod(method, source: token)

        case .header:
            guard let value else { return }
            try appendHeader(value, command: &command)

        case .body:
            guard let value else { return }
            guard token == "--data-raw" || !value.hasPrefix("@") else {
                command.warnings.append("File-backed request bodies are not represented yet.")
                return
            }
            command.usesDataBody = true
            command.bodyParts.append(value)

        case .jsonBody:
            guard let value else { return }
            guard !value.hasPrefix("@") else {
                command.warnings.append("File-backed request bodies are not represented yet.")
                return
            }
            if !command.headers.contains(where: { $0.name.caseInsensitiveCompare("Content-Type") == .orderedSame }) {
                command.appendHeader(name: "Content-Type", value: "application/json")
            }
            if !command.headers.contains(where: { $0.name.caseInsensitiveCompare("Accept") == .orderedSame }) {
                command.appendHeader(name: "Accept", value: "application/json")
            }
            command.bodyParts.append(value)

        case .url:
            guard let value else { return }
            if command.url == nil {
                command.url = value
            } else if command.url != value {
                command.warnings.append("URL from `--url` overrides earlier URL.")
                command.url = value
            }

        case .headerValue(let name):
            guard let value else { return }
            command.appendHeader(name: name, value: value)

        case .cookie:
            guard let value else { return }
            guard value.contains("=") else {
                command.warnings.append("Cookie files are not represented yet.")
                return
            }
            command.appendHeader(name: "Cookie", value: value)

        case .basicAuth:
            guard let value else { return }
            guard value.contains(":") else {
                throw CurlImportError.unsupportedSyntax("Auth shorthand without ':' is not supported yet.")
            }
            let encoded = Data(value.utf8).base64EncodedString()
            command.appendHeader(name: "Authorization", value: "Basic \(encoded)")

        case .head:
            command.setMethod(.head, source: token)

        case .multipartForm:
            if command.method == nil {
                command.setMethod(.post, source: token)
            }
            command.warnings.append("Multipart form data is not represented yet.")

        case .disableTLSCertificateVerification:
            command.disablesTLSCertificateVerification = true

        case .ignore:
            return

        case .warn(let warning):
            command.warnings.append(warning)

        case .warnValue(let warning):
            command.warnings.append(warning)
        }
    }

    private func appendHeader(_ rawHeader: String, command: inout CurlCommand) throws {
        if rawHeader.hasSuffix(";"), !rawHeader.contains(":") {
            let name = String(rawHeader.dropLast()).trimmingCharacters(in: .whitespacesAndNewlines)
            guard !name.isEmpty else {
                throw CurlImportError.malformedInput("Header name is empty.")
            }
            command.appendHeader(name: name, value: "")
            return
        }

        guard let separator = rawHeader.firstIndex(of: ":") else {
            throw CurlImportError.malformedInput("Header '\(rawHeader)' is missing ':'.")
        }

        let name = String(rawHeader[..<separator]).trimmingCharacters(in: .whitespacesAndNewlines)
        guard !name.isEmpty else {
            throw CurlImportError.malformedInput("Header name is empty.")
        }
        let value = String(rawHeader[rawHeader.index(after: separator)...]).trimmingCharacters(in: .whitespacesAndNewlines)
        guard !value.isEmpty else {
            command.suppressHeader(name: name)
            return
        }
        command.appendHeader(name: name, value: value)
    }
}

private struct CurlRequestMapper {
    func map(_ command: CurlCommand) throws -> Request {
        guard let url = command.url else {
            throw CurlImportError.missingURL
        }

        let body = command.bodyParts.isEmpty ? nil : command.bodyParts.joined(separator: "&")
        var headers = command.headers
        if body != nil,
           command.usesDataBody,
           !headers.contains(where: { $0.name.caseInsensitiveCompare("Content-Type") == .orderedSame }),
           !command.suppressedHeaderNames.contains("content-type") {
            headers.append(Header(name: "Content-Type", value: "application/x-www-form-urlencoded"))
        }

        return Request(
            method: command.method ?? (body == nil ? .get : .post),
            urlString: url,
            headers: headers,
            body: body.map(RequestBody.text) ?? .none,
            tlsCertificateVerification: command.disablesTLSCertificateVerification ? .disabled : .systemDefault
        )
    }
}

private enum ShellTokenizer {
    static func tokenize(_ input: String) throws -> [String] {
        var tokens: [String] = []
        var current = ""
        var activeQuote: Character?
        var tokenStarted = false
        var iterator = input.makeIterator()

        while let character = iterator.next() {
            if let quote = activeQuote {
                if character == quote {
                    activeQuote = nil
                } else if character == "\\" && quote == "\"" {
                    guard let escaped = iterator.next() else {
                        throw CurlImportError.malformedInput("Trailing escape sequence.")
                    }
                    try appendShellCharacter(escaped, to: &current)
                } else {
                    if quote != "'", character == "$" || character == "`" {
                        throw CurlImportError.unsupportedSyntax("Shell variables and command substitution are not supported in cURL import yet.")
                    }
                    current.append(character)
                }
                continue
            }

            switch character {
            case "\"", "'":
                activeQuote = character
                tokenStarted = true
            case " ", "\t", "\n":
                if tokenStarted {
                    tokens.append(current)
                    current = ""
                    tokenStarted = false
                }
            case "\\":
                guard let escaped = iterator.next() else {
                    throw CurlImportError.malformedInput("Trailing escape sequence.")
                }
                if escaped == "\n" {
                    continue
                }
                if escaped == "\r" {
                    if let nextCharacter = iterator.next(), nextCharacter != "\n" {
                        try appendShellCharacter(nextCharacter, to: &current)
                    }
                    continue
                }
                current.append(escaped)
                tokenStarted = true
            case "$", "`":
                throw CurlImportError.unsupportedSyntax("Shell variables and command substitution are not supported in cURL import yet.")
            default:
                current.append(character)
                tokenStarted = true
            }
        }

        if activeQuote != nil {
            throw CurlImportError.malformedInput("Unterminated quoted string.")
        }

        if tokenStarted {
            tokens.append(current)
        }

        return tokens
    }

    private static func appendShellCharacter(_ character: Character, to current: inout String) throws {
        if character == "$" || character == "`" {
            throw CurlImportError.unsupportedSyntax("Shell variables and command substitution are not supported in cURL import yet.")
        }
        current.append(character)
    }
}
